GET localhost:8080/api/product/all

###

GET localhost:8080/api/product/find?id=637fe442abb8aa051efffcc9

###

POST localhost:8080/api/product/save
Content-Type: application/json

{
  "calories": 1415,
  "author":"New",
  "price" :  720.0,
  "additionalFieldList": [
    {
      "fieldName": "Процент воды в супе",
      "fieldValue": "100"
    }
  ]
}

###

PUT localhost:8080/api/product/update
Content-Type: application/json

{
  "id": "638b5df28f1ada1f66416562",
  "calories": 1415,
  "author":"New",
  "price" :  720.0,
  "additionalFieldList": [
    {
      "fieldName": "Процент воды в супе",
      "fieldValue": "100"
    }
    ],
  "name" : "Украинский борщ"
}

###

DELETE localhost:8080/api/product/delete?id=6380c6d9a3b2b71de2012e53